---

- name: mix | install mix dependencies
  command: "mix {{ item.name }} --force"
  args:
    creates: "{{ phoenix_app_path }}/.mix/{{ item.file }}"
  become: yes
  become_user: "{{ phoenix_app_user }}"
  with_items:
    - { name: "local.hex",   file: "archives/hex.ez" }
    - { name: "local.rebar", file: "rebar" }

- name: mix | install phoenix
  command: mix archive.install https://github.com/phoenixframework/archives/raw/master/phoenix_new-{{ phoenix_app_framework_version }}.ez --force
  args:
    creates: "{{ phoenix_app_path }}/.mix/archives/phoenix_new-{{ phoenix_app_framework_version }}.ez"
  become: yes
  become_user: "{{ phoenix_app_user }}"

- name: packages | Install
  apt:
    name: git-core
    update_cache: yes
    cache_valid_time: 3600
    state: present
  become: yes

- name: packages | Install brunch
  npm:
    name: brunch
    global: yes
    state: present
  become: yes
  when: phoenix_app_run_brunch

